# Generated by Django 3.1.13 on 2022-07-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220704_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.productnamemodel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.tagmodel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='weight',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.weightmodel'),
            preserve_default=False,
        ),
    ]
